//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ogrtbl
    {
        public int id { get; set; }
        [Display(Name = "Öðrencinin Adý")]
        [Required(ErrorMessage = "Bu alaný girmek zorunludur.")]
        public string ad { get; set; }
        [Display(Name = "Öðrencinin Soyadý")]
        [Required(ErrorMessage ="Bu alaný girmek zorunludur.")]
        public string soyad { get; set; }
        [Display(Name = "Öðrenci Numarasý")]
        [Required(ErrorMessage = "Bu alaný girmek zorunludur.")]
        [Range(100000000,999999999,ErrorMessage ="Öðrenci Numarasý 9 haneli sayý olmak zorundadýr")]

        public Nullable<int> ogrno { get; set; }

    }
}
